### PR TITLE
Added some primitive device firmware resource endpoints for Meshtastic-flasher

### PR DESCRIPTION
**Pull request by thebentern**
As requested by @mkinney. 
Still needs app auth added and some polish, and I don't know anything about the deployment environment.

@sachaw, you have more chops on the Github integration stuff so maybe you can shed some light on this. I'd like to have a **/device/firmware/latest** route that would return in the same format as the resources I added, which would serve the url to the artifact zip of the latest successful action run on the master branch. 

From my brief foray into octokit / github rest api, it would seem that they have made it very obtuse to traverse the very loose relationships between workflow suites / runs / artifacts to branches, pull requests, etc. I was able to circumvent this on PRs by augmenting our github action to add a comment with a link to firmware, which I think adds value to the github experience but also made it significantly easier to scrape that information up for the endpoint.

### CODE REVIEW

**Review by mkinney — APPROVED** [review]
I'm not very familiar with Typescript.

**Comment by thebentern** [comment]
Pull-request output for posterity because I'm about to merge the last PR with an artifact
`[
    {
        "id": "1183",
        "title": "Adjusted adc_multiplier for heltec2.1 and added adc_mulitplier_override",
        "page_url": "https://github.com/meshtastic/Meshtastic-device/pull/1183",
        "zip_url": "https://github.com/meshtastic/Meshtastic-device/blob/artifacts/pr1183-firmware-1.2.53.856f2f9.zip?raw=true"
    }
]`

**Comment by sachaw** [comment]
I'll get around to adding a prettier and eslint config so we have linting but that can wait.

I'll do some tweaking and verification tonight then I can merge it

**Comment by sachaw** [comment]
Not sure if working as expected yet, but we can continue to work on it in master if needed

**Pull request merged**
